//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Art_Gallery.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class Blog
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Picture { get; set; }
        [AllowHtml]
        public string Detail { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Descreption { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
