//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Art_Gallery.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class Exhibition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exhibition()
        {
            this.OrderExhibitions = new HashSet<OrderExhibition>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Picture { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public Nullable<double> Starting_Price { get; set; }
        public string Address { get; set; }
        public Nullable<int> Owner { get; set; }
        [AllowHtml]
        public string Detail { get; set; }
        public string Descreption { get; set; }
        public Nullable<bool> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderExhibition> OrderExhibitions { get; set; }
    }
}
